"""Operation model — every modification is a replayable, serializable record.

The AI builds geometry through a sequence of operations. Each operation
is logged so we can: undo, replay, export as CadQuery script, and audit
what the AI did.
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any
from uuid import uuid4

from pydantic import BaseModel, Field


class OpType(str, Enum):
    """All supported modeling operations."""

    # Create
    CREATE_BOX = "create_box"
    CREATE_CYLINDER = "create_cylinder"
    CREATE_SPHERE = "create_sphere"
    CREATE_CONE = "create_cone"
    CREATE_EXTRUSION = "create_extrusion"

    # Modify
    ADD_HOLE = "add_hole"
    ADD_COUNTERBORE_HOLE = "add_counterbore_hole"
    ADD_COUNTERSINK_HOLE = "add_countersink_hole"
    ADD_POCKET = "add_pocket"
    ADD_CIRCULAR_POCKET = "add_circular_pocket"
    ADD_BOSS = "add_boss"
    ADD_SLOT = "add_slot"
    ADD_FILLET = "add_fillet"
    ADD_CHAMFER = "add_chamfer"

    # Boolean
    BOOLEAN_UNION = "boolean_union"
    BOOLEAN_CUT = "boolean_cut"
    BOOLEAN_INTERSECT = "boolean_intersect"

    # Transform
    TRANSLATE = "translate"
    ROTATE = "rotate"
    MIRROR = "mirror"

    # Pattern
    LINEAR_PATTERN = "linear_pattern"
    CIRCULAR_PATTERN = "circular_pattern"

    # Advanced create
    CREATE_REVOLVE = "create_revolve"
    CREATE_SWEEP = "create_sweep"
    CREATE_LOFT = "create_loft"

    # Advanced modify
    ADD_SHELL = "add_shell"
    ADD_DRAFT = "add_draft"

    # Multi-body
    CREATE_NAMED_BODY = "create_named_body"
    SET_ACTIVE_BODY = "set_active_body"
    DELETE_BODY = "delete_body"
    BOOLEAN_BODIES = "boolean_bodies"

    # Assembly
    PLACE_BODY = "place_body"
    ADD_MATE = "add_mate"

    # GD&T
    ADD_DATUM = "add_datum"
    ADD_TOLERANCE = "add_tolerance"

    # Sketch
    CREATE_SKETCH = "create_sketch"
    SKETCH_ADD_LINE = "sketch_add_line"
    SKETCH_ADD_ARC = "sketch_add_arc"
    SKETCH_ADD_CIRCLE = "sketch_add_circle"
    SKETCH_ADD_RECT = "sketch_add_rect"
    SKETCH_ADD_CONSTRAINT = "sketch_add_constraint"
    SKETCH_EXTRUDE = "sketch_extrude"
    SKETCH_REVOLVE = "sketch_revolve"

    # Topology optimization
    ADD_LOAD = "add_load"
    ADD_BOUNDARY_CONDITION = "add_boundary_condition"
    RUN_TOPOLOGY_OPT = "run_topology_opt"

    # File
    LOAD_STEP = "load_step"
    EXPORT_STL = "export_stl"
    EXPORT_3MF = "export_3mf"
    EXPORT_ASSEMBLY = "export_assembly"
    RENDER_PNG = "render_png"


class Operation(BaseModel):
    """A single modeling operation — the atomic unit of the operation log."""

    op_id: str = Field(default_factory=lambda: uuid4().hex[:12])
    op_type: OpType
    params: dict[str, Any] = Field(default_factory=dict)
    timestamp: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    description: str = ""

    model_config = {"use_enum_values": True}


class OperationLog(BaseModel):
    """Ordered sequence of operations forming the parametric history.

    This is what STEP files don't have — the recipe, not just the result.
    """

    operations: list[Operation] = Field(default_factory=list)

    def append(self, op: Operation) -> None:
        self.operations.append(op)

    def pop(self) -> Operation | None:
        """Remove and return the last operation (for undo)."""
        if self.operations:
            return self.operations.pop()
        return None

    @property
    def length(self) -> int:
        return len(self.operations)

    def to_cadquery_script(self) -> str:
        """Export the operation log as a standalone CadQuery Python script.

        This is the AI's construction history, human-readable and replayable.
        """
        lines = [
            "import cadquery as cq",
            "",
            "# Auto-generated by next3d modeling session",
            f"# {self.length} operations",
            "",
        ]

        var_counter = 0
        var_name = "result"

        for op in self.operations:
            var_counter += 1
            p = op.params
            ot = op.op_type

            if ot == OpType.CREATE_BOX:
                line = (
                    f'{var_name} = cq.Workplane("XY").box('
                    f'{p["length"]}, {p["width"]}, {p["height"]})'
                )
            elif ot == OpType.CREATE_CYLINDER:
                line = (
                    f'{var_name} = cq.Workplane("XY").cylinder('
                    f'{p["height"]}, {p["radius"]})'
                )
            elif ot == OpType.CREATE_SPHERE:
                line = (
                    f'{var_name} = cq.Workplane("XY").sphere({p["radius"]})'
                )
            elif ot == OpType.ADD_HOLE:
                sel = p.get("face_selector", ">Z")
                depth_arg = ""
                if p.get("depth") is not None:
                    depth_arg = f', {p["depth"]}'
                line = (
                    f'{var_name} = {var_name}.faces("{sel}").workplane()'
                    f'.pushPoints([({p["center_x"]}, {p["center_y"]})])'
                    f'.hole({p["diameter"]}{depth_arg})'
                )
            elif ot == OpType.ADD_POCKET:
                sel = p.get("face_selector", ">Z")
                line = (
                    f'{var_name} = {var_name}.faces("{sel}").workplane()'
                    f'.center({p["center_x"]}, {p["center_y"]})'
                    f'.rect({p["length"]}, {p["width"]})'
                    f'.cutBlind(-{p["depth"]})'
                )
            elif ot == OpType.ADD_BOSS:
                sel = p.get("face_selector", ">Z")
                line = (
                    f'{var_name} = {var_name}.faces("{sel}").workplane()'
                    f'.center({p["center_x"]}, {p["center_y"]})'
                    f'.circle({p["diameter"] / 2})'
                    f'.extrude({p["height"]})'
                )
            elif ot == OpType.ADD_FILLET:
                sel = p.get("edge_selector", "")
                if sel:
                    line = f'{var_name} = {var_name}.edges("{sel}").fillet({p["radius"]})'
                else:
                    line = f'{var_name} = {var_name}.edges().fillet({p["radius"]})'
            elif ot == OpType.ADD_CHAMFER:
                sel = p.get("edge_selector", "")
                if sel:
                    line = f'{var_name} = {var_name}.edges("{sel}").chamfer({p["distance"]})'
                else:
                    line = f'{var_name} = {var_name}.edges().chamfer({p["distance"]})'
            elif ot == OpType.ADD_SLOT:
                sel = p.get("face_selector", ">Z")
                line = (
                    f'{var_name} = {var_name}.faces("{sel}").workplane()'
                    f'.center({p["center_x"]}, {p["center_y"]})'
                    f'.slot2D({p["length"]}, {p["width"]})'
                    f'.cutBlind(-{p["depth"]})'
                )
            elif ot == OpType.ADD_SHELL:
                sel = p.get("face_selector", ">Z")
                line = (
                    f'{var_name} = {var_name}.faces("{sel}")'
                    f'.shell({p["thickness"]})'
                )
            elif ot == OpType.CREATE_REVOLVE:
                line = f"# Revolve: profile={p.get('points', [])}, angle={p.get('angle_degrees', 360)}"
            elif ot == OpType.CREATE_SWEEP:
                line = f"# Sweep: profile along path"
            elif ot == OpType.CREATE_LOFT:
                line = f"# Loft: {len(p.get('sections', []))} sections"
            elif ot == OpType.LOAD_STEP:
                line = f'{var_name} = cq.importers.importStep("{p["path"]}")'
            else:
                line = f"# {ot}: {p}"

            if op.description:
                line += f"  # {op.description}"

            lines.append(line)

        lines.append("")
        lines.append("# Export")
        lines.append('cq.exporters.export(result, "output.step")')
        lines.append("")

        return "\n".join(lines)
